# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc55d1522fa7c85fbde0f80b1be30699d2541b65565776bcd1250ba26c4293eba5da5cde2b40c1a6e956a6687c2cc0cccacb77371cc5dff70004277071248001

test:
  secret_key_base: 03b9c2b5a56c6d5785740a875b747ee96e538b5ddf944dd522d3b2b925b6a5e3ba661945b8059a32712330fd221d5f9490e3178bcdccc8f8d6be285236fa34eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
